---

_You are currently looking at **version 1.1** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

In [1]:
import pandas as pd
import numpy as np
from scipy.stats import ttest_ind

# Assignment 4 - Hypothesis Testing
This assignment requires more individual learning than previous assignments - you are encouraged to check out the [pandas documentation](http://pandas.pydata.org/pandas-docs/stable/) to find functions or methods you might not have used yet, or ask questions on [Stack Overflow](http://stackoverflow.com/) and tag them as pandas and python related. And of course, the discussion forums are open for interaction with your peers and the course staff.

Definitions:
* A _quarter_ is a specific three month period, Q1 is January through March, Q2 is April through June, Q3 is July through September, Q4 is October through December.
* A _recession_ is defined as starting with two consecutive quarters of GDP decline, and ending with two consecutive quarters of GDP growth.
* A _recession bottom_ is the quarter within a recession which had the lowest GDP.
* A _university town_ is a city which has a high percentage of university students compared to the total population of the city.

**Hypothesis**: University towns have their mean housing prices less effected by recessions. Run a t-test to compare the ratio of the mean price of houses in university towns the quarter before the recession starts compared to the recession bottom. (`price_ratio=quarter_before_recession/recession_bottom`)

The following data files are available for this assignment:
* From the [Zillow research data site](http://www.zillow.com/research/data/) there is housing data for the United States. In particular the datafile for [all homes at a city level](http://files.zillowstatic.com/research/public/City/City_Zhvi_AllHomes.csv), ```City_Zhvi_AllHomes.csv```, has median home sale prices at a fine grained level.
* From the Wikipedia page on college towns is a list of [university towns in the United States](https://en.wikipedia.org/wiki/List_of_college_towns#College_towns_in_the_United_States) which has been copy and pasted into the file ```university_towns.txt```.
* From Bureau of Economic Analysis, US Department of Commerce, the [GDP over time](http://www.bea.gov/national/index.htm#gdp) of the United States in current dollars (use the chained value in 2009 dollars), in quarterly intervals, in the file ```gdplev.xls```. For this assignment, only look at GDP data from the first quarter of 2000 onward.

Each function in this assignment below is worth 10%, with the exception of ```run_ttest()```, which is worth 50%.

In [10]:
# Use this dictionary to map state names to two letter acronyms
states = {'OH': 'Ohio', 'KY': 'Kentucky', 'AS': 'American Samoa', 'NV': 'Nevada', 'WY': 'Wyoming', 'NA': 'National', 'AL': 'Alabama', 'MD': 'Maryland', 'AK': 'Alaska', 'UT': 'Utah', 'OR': 'Oregon', 'MT': 'Montana', 'IL': 'Illinois', 'TN': 'Tennessee', 'DC': 'District of Columbia', 'VT': 'Vermont', 'ID': 'Idaho', 'AR': 'Arkansas', 'ME': 'Maine', 'WA': 'Washington', 'HI': 'Hawaii', 'WI': 'Wisconsin', 'MI': 'Michigan', 'IN': 'Indiana', 'NJ': 'New Jersey', 'AZ': 'Arizona', 'GU': 'Guam', 'MS': 'Mississippi', 'PR': 'Puerto Rico', 'NC': 'North Carolina', 'TX': 'Texas', 'SD': 'South Dakota', 'MP': 'Northern Mariana Islands', 'IA': 'Iowa', 'MO': 'Missouri', 'CT': 'Connecticut', 'WV': 'West Virginia', 'SC': 'South Carolina', 'LA': 'Louisiana', 'KS': 'Kansas', 'NY': 'New York', 'NE': 'Nebraska', 'OK': 'Oklahoma', 'FL': 'Florida', 'CA': 'California', 'CO': 'Colorado', 'PA': 'Pennsylvania', 'DE': 'Delaware', 'NM': 'New Mexico', 'RI': 'Rhode Island', 'MN': 'Minnesota', 'VI': 'Virgin Islands', 'NH': 'New Hampshire', 'MA': 'Massachusetts', 'GA': 'Georgia', 'ND': 'North Dakota', 'VA': 'Virginia'}

In [2]:
def get_list_of_university_towns():
    '''Returns a DataFrame of towns and the states they are in from the 
    university_towns.txt list. The format of the DataFrame should be:
    DataFrame( [ ["Michigan", "Ann Arbor"], ["Michigan", "Yipsilanti"] ], 
    columns=["State", "RegionName"]  )
    
    The following cleaning needs to be done:

    1. For "State", removing characters from "[" to the end.
    2. For "RegionName", when applicable, removing every character from " (" to the end.
    3. Depending on how you read the data, you may need to remove newline character '\n'. '''
    
    import re
    import pandas as pd

    # Open the file, read the lines, and close the file
    fo = open('university_towns.txt', "r")
    lines = fo.readlines()
    fo.close()

    # remove empty lines
    new_lines = []
    for line in lines:
        if not re.match(r'^\s*$', line):
            new_lines.append(line)

    lines = new_lines.copy()

    # Strip the white space at the beginning and end of each line
    for index, line in enumerate(lines):
        lines[index] = line.strip()

        # Loop through the lines to form a dataframe
    df_result = pd.DataFrame(columns=('State', 'RegionName'))
    i = 0  # counter for each new line in the dataframe
    state_string = ""  # Empty initial state string
    region_string = ""  # Empty initial region string
    for line in lines:
        if '[edit]' in line:
            state_string = line.replace('[edit]', "") #remove every character from "[" to the end
        else:
            region_string = re.sub(r' \(.*', "", line) #removing every character from " (" to the end
            df_result.loc[i] = [state_string, region_string]
            i += 1
            
    return df_result
get_list_of_university_towns()

             State                    RegionName
0          Alabama                        Auburn
1          Alabama                      Florence
2          Alabama                  Jacksonville
3          Alabama                    Livingston
4          Alabama                    Montevallo
5          Alabama                          Troy
6          Alabama                    Tuscaloosa
7          Alabama                      Tuskegee
8           Alaska                     Fairbanks
9          Arizona                     Flagstaff
10         Arizona                         Tempe
11         Arizona                        Tucson
12        Arkansas                   Arkadelphia
13        Arkansas                        Conway
14        Arkansas                  Fayetteville
15        Arkansas                     Jonesboro
16        Arkansas                      Magnolia
17        Arkansas                    Monticello
18        Arkansas                  Russellville
19        Arkansas                        Searcy
20      California                        Angwin
21      California                        Arcata
22      California                      Berkeley
23      California                         Chico
24      California                     Claremont
25      California                        Cotati
26      California                         Davis
27      California                        Irvine
28      California                    Isla Vista
29      California  University Park, Los Angeles
..             ...                           ...
487       Virginia                          Wise
488       Virginia                    Chesapeake
489     Washington                    Bellingham
490     Washington                        Cheney
491     Washington                    Ellensburg
492     Washington                       Pullman
493     Washington  University District, Seattle
494  West Virginia                        Athens
495  West Virginia                    Buckhannon
496  West Virginia                      Fairmont
497  West Virginia                     Glenville
498  West Virginia                    Huntington
499  West Virginia                    Montgomery
500  West Virginia                    Morgantown
501  West Virginia                 Shepherdstown
502  West Virginia                  West Liberty
503      Wisconsin                      Appleton
504      Wisconsin                    Eau Claire
505      Wisconsin                     Green Bay
506      Wisconsin                     La Crosse
507      Wisconsin                       Madison
508      Wisconsin                     Menomonie
509      Wisconsin                     Milwaukee
510      Wisconsin                       Oshkosh
511      Wisconsin                   Platteville
512      Wisconsin                   River Falls
513      Wisconsin                 Stevens Point
514      Wisconsin                      Waukesha
515      Wisconsin                    Whitewater
516        Wyoming                       Laramie

[517 rows x 2 columns]

In [7]:
def get_recession_start():
    '''Returns the year and quarter of the recession start time as a 
    string value in a format such as 2005q3'''

    import pandas as pd
    df_gdp = pd.read_excel('gdplev.xls', skiprows=220, parse_cols='E,G', header=None)
    df_gdp.columns = ['quarter', 'GDP']

    for i in range(4, len(df_gdp)):
        if (df_gdp.loc[i-4, 'GDP'] > df_gdp.loc[i-3, 'GDP']) \
                and (df_gdp.loc[i-3, 'GDP'] > df_gdp.loc[i-2, 'GDP']) \
                and (df_gdp.loc[i-2, 'GDP'] < df_gdp.loc[i-1, 'GDP']) \
                and (df_gdp.loc[i-1, 'GDP'] < df_gdp.loc[i, 'GDP']):
            recession_base_idx = i-4
    
    result = df_gdp.loc[recession_base_idx, 'quarter']
    j = recession_base_idx
    while True:
        if (df_gdp.loc[j-1, 'GDP'] > df_gdp.loc[j, 'GDP']):
            j -= 1
        else:
            result = df_gdp.loc[j+1, 'quarter']
            break
        
    return result

get_recession_start()

'2008q3'

In [5]:
def get_recession_end():
    '''Returns the year and quarter of the recession end time as a 
    string value in a format such as 2005q3'''

    import pandas as pd
    df_gdp = pd.read_excel('gdplev.xls', skiprows=220, parse_cols='E,G', header=None)
    df_gdp.columns = ['quarter', 'GDP']

    for i in range(4, len(df_gdp)):
        if (df_gdp.loc[i-4, 'GDP'] > df_gdp.loc[i-3, 'GDP']) \
                and (df_gdp.loc[i-3, 'GDP'] > df_gdp.loc[i-2, 'GDP']) \
                and (df_gdp.loc[i-2, 'GDP'] < df_gdp.loc[i-1, 'GDP']) \
                and (df_gdp.loc[i-1, 'GDP'] < df_gdp.loc[i, 'GDP']):
            result = df_gdp.loc[i, 'quarter']

    return result

get_recession_end()

'2009q4'

In [6]:
def get_recession_bottom():
    '''Returns the year and quarter of the recession bottom time as a 
    string value in a format such as 2005q3'''

    import pandas as pd
    df_gdp = pd.read_excel('gdplev.xls', skiprows=220, parse_cols='E,G', header=None)
    df_gdp.columns = ['quarter', 'GDP']

    for i in range(4, len(df_gdp)):
        if (df_gdp.loc[i-4, 'GDP'] > df_gdp.loc[i-3, 'GDP']) \
                and (df_gdp.loc[i-3, 'GDP'] > df_gdp.loc[i-2, 'GDP']) \
                and (df_gdp.loc[i-2, 'GDP'] < df_gdp.loc[i-1, 'GDP']) \
                and (df_gdp.loc[i-1, 'GDP'] < df_gdp.loc[i, 'GDP']):
            result = df_gdp.loc[i-2, 'quarter']

    return result

get_recession_bottom()

'2009q2'

In [8]:
pd.read_csv('City_Zhvi_AllHomes.csv', header=0)

,RegionID,RegionName,State,Metro,CountyName,SizeRank,1996-04,1996-05,1996-06,1996-07,...,2015-11,2015-12,2016-01,2016-02,2016-03,2016-04,2016-05,2016-06,2016-07,2016-08
0,6181,New York,NY,New York,Queens,1,NaN,NaN,NaN,NaN,...,573600,576200,578400,582200,588000,592200,592500,590200,588000,586400
1,12447,Los Angeles,CA,Los Angeles-Long Beach-Anaheim,Los Angeles,2,155000.0,154600.0,154400.0,154200.0,...,558200,560800,562800,565600,569700,574000,577800,580600,583000,585100
2,17426,Chicago,IL,Chicago,Cook,3,109700.0,109400.0,109300.0,109300.0,...,207800,206900,206200,205800,206200,207300,208200,209100,211000,213000
3,13271,Philadelphia,PA,Philadelphia,Philadelphia,4,50000.0,49900.0,49600.0,49400.0,...,122300,121600,121800,123300,125200,126400,127000,127400,128300,129100
4,40326,Phoenix,AZ,Phoenix,Maricopa,5,87200.0,87700.0,88200.0,88400.0,...,183800,185300,186600,188000,189100,190200,191300,192800,194500,195900
5,18959,Las Vegas,NV,Las Vegas,Clark,6,121600.0,120900.0,120400.0,120300.0,...,190600,192000,193600,194800,195400,196100,197300,198200,199300,200600
6,54296,San Diego,CA,San Diego,San Diego,7,161100.0,160700.0,160400.0,160100.0,...,525700,526700,527800,529200,531000,533900,536900,537900,539000,540500
7,38128,Dallas,TX,Dallas-Fort Worth,Dallas,8,NaN,NaN,NaN,NaN,...,134600,136600,138700,140600,142200,143300,144500,146000,148200,150400
8,33839,San Jose,CA,San Jose,Santa Clara,9,224500.0,224900.0,225400.0,226100.0,...,789700,792100,795800,803100,811900,817600,819100,820100,821700,822700
9,25290,Jacksonville,FL,Jacksonville,Duval,10,77500.0,77200.0,76800.0,76600.0,...,132000,132500,133100,133900,134900,136000,137200,138400,139500,140300
10,20330,San Francisco,CA,San Francisco,San Francisco,11,262500.0,263500.0,264100.0,265000.0,...,1105800,1112300,1117400,1122700,1125200,1123200,1119800,1114800,1108800,1104000
11,10221,Austin,TX,Austin,Travis,12,NaN,NaN,NaN,NaN,...,287300,289300,291100,293400,296000,299200,301800,303300,304100,304800
12,17762,Detroit,MI,Detroit,Wayne,13,NaN,NaN,NaN,NaN,...,38500,38400,38300,38000,37600,37400,37500,37500,37700,38100
13,10920,Columbus,OH,Columbus,Franklin,14,83100.0,83200.0,83300.0,83500.0,...,115200,115800,116200,116700,117200,117700,118100,118800,119700,120500
14,32811,Memphis,TN,Memphis,Shelby,15,60600.0,60500.0,60700.0,60800.0,...,69600,69800,69900,70800,72000,73100,74300,75100,75600,76200
15,24043,Charlotte,NC,Charlotte,Mecklenburg,16,94500.0,94900.0,95700.0,96400.0,...,162800,164300,165500,166500,167400,168400,169500,170400,171700,173100
16,17933,El Paso,TX,El Paso,El Paso,17,67400.0,67800.0,68000.0,68300.0,...,110200,110000,110200,110600,111200,111500,111400,111500,112100,112300
17,44269,Boston,MA,Boston,Suffolk,18,123100.0,122800.0,123100.0,123800.0,...,471000,474600,478700,482900,486200,488000,489700,493400,499200,504200
18,16037,Seattle,WA,Seattle,King,19,164400.0,163900.0,163600.0,163400.0,...,533700,538700,544300,551200,559700,568600,576200,581800,587200,592200
19,3523,Baltimore,MD,Baltimore,Baltimore City,20,53200.0,53900.0,54400.0,54700.0,...,113600,114000,114500,114700,114800,114700,114600,114900,115100,115200
20,11093,Denver,CO,Denver,Denver,21,98700.0,99200.0,99600.0,100200.0,...,330500,332100,333500,335600,337600,339700,342700,345900,349800,353300
21,41568,Washington,DC,Washington,District of Columbia,22,NaN,NaN,NaN,NaN,...,501200,502500,503800,504700,503800,503400,505100,508900,513900,518600
22,6118,Nashville,TN,Nashville,Davidson,23,83100.0,83800.0,84800.0,85900.0,...,189300,191400,193300,195100,196800,198400,200300,202400,205000,207200
23,5976,Milwaukee,WI,Milwaukee,Milwaukee,24,68100.0,68100.0,68100.0,67800.0,...,94600,94300,94200,94600,95200,95900,96300,96900,98200,99500
24,7481,Tucson,AZ,Tucson,Pima,25,91500.0,91500.0,91600.0,91500.0,...,148200,148400,148800,149500,150300,150700,151100,151700,152400,153000
25,13373,Portland,OR,Portland,Multnomah,26,121100.0,122200.0,123000.0,123600.0,...,343400,347800,351900,356100,360000,364400,369300,375700,383600,390500
26,33225,Oklahoma City,OK,Oklahoma City,Oklahoma,27,64900.0,65400.0,65700.0,65800.0,...,127300,127700,127600,127700,128400,129000,129300,129600,130100,130500
27,40152,Omaha,NE,Omaha,Douglas,28,88900.0,89600.0,90400.0,90800.0,...,140300,140500,140900,141600,142400,142800,142700,142500,143100,143800
28,23429,Albuquerque,NM,Albuquerque,Bernalillo,29,115400.0,115600.0,116000.0,116700.0,...,167300,167800,168300,169100,169900,170300,170500,171100,171800,172000
29,18203,Fresno,CA,Fresno,Fresno,30,90400.0,90400.0,90200.0,90000.0,...,187600,187700,187900,189000,190200,191200,192700,194300,195800,197100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10700,49199,Granite Shoals,TX,NaN,Burnet,10701,NaN,NaN,NaN,NaN,...,128200,129900,131500,133700,136100,137900,139700,142600,145700,147200
10701,49693,Piney Point,MD,California-Lexington Park,Saint Marys,10702,148400.0,152300.0,153600.0,153100.0,...,309800,312600,315900,319900,322700,323600,324300,324600,324500,324700
10702,50374,Maribel,WI,Manitowoc,Manitowoc,10703,NaN,NaN,NaN,NaN,...,129100,129700,128900,127600,127000,127800,129300,130700,132900,135500
10703,50539,Middleton,ID,Boise City,Canyon,10704,103100.0,103200.0,103300.0,103000.0,...,151100,152300,153200,154000,154500,155500,157200,158800,160100,161400
10704,50963,Bennett,CO,Denver,Adams,10705,83800.0,85900.0,87100.0,88100.0,...,195700,197400,198500,199400,201400,204500,207700,210200,211900,213300
10705,51793,East Hampstead,NH,Boston,Rockingham,10706,132200.0,128600.0,125500.0,125200.0,...,269600,270600,271200,272400,274000,275800,277800,279800,281700,283200
10706,52166,Garden City,MO,Kansas City,Cass,10707,NaN,NaN,NaN,NaN,...,103600,104800,105200,105800,107800,110000,112000,113000,113500,113700
10707,53456,Mountainburg,AR,Fort Smith,Crawford,10708,55600.0,55500.0,55400.0,56200.0,...,90100,93400,96300,98600,100100,101200,101800,102700,103300,103500
10708,53730,Oostburg,WI,Sheboygan,Sheboygan,10709,86300.0,84900.0,83800.0,83700.0,...,132000,132500,132700,132600,133000,133700,134100,134500,135700,137000
10709,54771,Twin Peaks,CA,Riverside,San Bernardino,10710,85500.0,85200.0,84600.0,84400.0,...,159200,160600,162400,164400,165700,166300,167700,169900,172500,174500
10710,54802,Upper Brookville,NY,New York,Nassau,10711,897200.0,894000.0,891300.0,894400.0,...,1833700,1854900,1879300,1905900,1928300,1941800,1942000,1948400,1962600,1975000
10711,54995,Volcano,HI,Hilo,Hawaii,10712,114600.0,108600.0,102400.0,96700.0,...,232500,236400,239700,241800,244700,247800,249600,249500,248500,247200
10712,55072,Wedgefield,SC,Sumter,Sumter,10713,NaN,NaN,NaN,NaN,...,69000,68500,68200,68500,69900,71900,74100,76800,79600,81800
10713,55210,Williamston,MI,Lansing,Ingham,10714,120900.0,124800.0,128200.0,130200.0,...,182700,181800,180800,181000,182600,182900,182200,182100,182800,183200
10714,55357,Decatur,AR,Fayetteville,Benton,10715,54700.0,55100.0,55100.0,54700.0,...,97200,97400,96900,96300,96300,96600,96600,96700,96900,96800
10715,55476,Briceville,TN,Knoxville,Anderson,10716,37000.0,37500.0,36700.0,36100.0,...,43200,41700,40800,40500,41100,41700,42000,41700,41100,40600
10716,55706,Edgewood,IN,Indianapolis,Madison,10717,NaN,NaN,NaN,NaN,...,100200,101100,100200,98900,99200,99600,99900,100400,101000,100900
10717,56183,Palmyra,TN,Clarksville,Montgomery,10718,NaN,NaN,NaN,NaN,...,126400,127600,127300,127300,128400,130000,133000,135600,137000,138500
10718,56845,Saint Inigoes,MD,California-Lexington Park,Saint Marys,10719,137400.0,136900.0,137500.0,138600.0,...,277200,275800,276300,279500,282200,282900,282900,282100,281400,281400
10719,56943,Marysville,IN,Louisville/Jefferson County,Clark,10720,NaN,NaN,NaN,NaN,...,119800,124100,127200,129500,128000,124800,122700,122200,123100,125300
10720,57212,Forest Falls,CA,Riverside,San Bernardino,10721,76400.0,75600.0,74100.0,73100.0,...,199700,195300,190400,187500,188000,190000,190600,189000,187100,186200
10721,171874,Bois D Arc,MO,Springfield,Greene,10722,77700.0,77500.0,77700.0,78600.0,...,149800,149100,148000,146900,145700,145000,143700,142600,143200,144800
10722,182023,Henrico,VA,Richmond,Henrico,10723,110200.0,110500.0,110900.0,111100.0,...,213800,215100,216000,216200,215900,215900,215900,216800,219000,221300
10723,188693,Diamond Beach,NJ,Ocean City,Cape May,10724,136500.0,136800.0,137000.0,135200.0,...,400100,401600,403100,405000,405500,404500,403800,403400,400700,397300
10724,227014,Gruetli Laager,TN,NaN,Grundy,10725,24800.0,24300.0,24500.0,25000.0,...,71800,72900,74500,75700,75800,75900,76600,76900,77200,77800
10725,398292,Town of Wrightstown,WI,Green Bay,Brown,10726,NaN,NaN,NaN,NaN,...,149900,150100,150300,150000,149200,149900,151400,152500,154100,155900
10726,398343,Urbana,NY,Corning,Steuben,10727,66900.0,65800.0,65500.0,65100.0,...,135700,136400,137700,138700,140500,143600,145000,144000,143000,143000
10727,398496,New Denmark,WI,Green Bay,Brown,10728,NaN,NaN,NaN,NaN,...,188700,189800,190800,191200,191200,191700,192800,194000,196300,198900
10728,398839,Angels,CA,NaN,Calaveras,10729,115600.0,116400.0,118000.0,119000.0,...,280400,279600,278000,276600,275000,273700,272000,269100,269000,270900
10729,399114,Holland,WI,Sheboygan,Sheboygan,10730,129900.0,130200.0,130300.0,129100.0,...,217800,219400,221100,222000,222800,224900,228000,231200,233900,236000

In [11]:
def convert_housing_data_to_quarters():
    '''Converts the housing data to quarters and returns it as mean 
    values in a dataframe. This dataframe should be a dataframe with
    columns for 2000q1 through 2016q3, and should have a multi-index
    in the shape of ["State","RegionName"].

    Note: Quarters are defined in the assignment description, they are
    not arbitrary three month periods.

    The resulting dataframe should have 67 columns, and 10,730 rows.
    '''

    import pandas as pd
    import numpy as np
    df = pd.read_csv('City_Zhvi_AllHomes.csv', header=0)
    
    # Create columns to keep
    cols_to_keep = ['RegionID', 'RegionName', 'State']
    for i in range(2000, 2017):
        for j in range(1, 13):
            if j <= 9:
                if i == 2016 and j == 9:
                    pass
                else:
                    month_str = '0' + str(j)
            else:
                if i == 2016:
                    pass
                else:
                    month_str = str(j)
            cols_to_keep.append(str(i) + '-' + month_str)
    df = df[cols_to_keep]
    
    # Convert two letter state abbreviations to state names
    df['State'] = df['State'].replace(states)

    def convert_to_qtr(ym):
        year, month = ym.split('-')
        if month == '01' or month == '02' or month == '03':
            result = year + 'q1'
        elif month == '04' or month == '05' or month == '06':
            result = year + 'q2'
        elif month == '07' or month == '08' or month == '09':
            result = year + 'q3'
        else:
            result = year + 'q4'
        return result

    # Stack the columns of GDP values and add a quarter column
    df_compiled = df.copy().set_index(['State', 'RegionName', 'RegionID']).stack(dropna=False)
    df_compiled = df_compiled.reset_index().rename(columns={'level_3': 'year_month', 0: 'gdp'})
    df_compiled.drop_duplicates(inplace=True)
    df_compiled['quarter'] = df_compiled['year_month'].apply(convert_to_qtr)
    df_compiled = df_compiled.drop('year_month', axis=1)
    result = df_compiled.pivot_table(values='gdp', index=['State', 'RegionName', 'RegionID'], columns='quarter', aggfunc=np.mean)
    result = result.reset_index()
    result = result.drop('RegionID', axis=1)
    #del result.index.name
    result = result.set_index(['State', 'RegionName'])
    return result

convert_housing_data_to_quarters()
#convert_housing_data_to_quarters().loc["Texas"].loc["Austin"].loc["2010q3"]

quarter                           2000q1         2000q2         2000q3  \
State     RegionName
Alabama   Adamsville        69033.333333   69166.666667   69800.000000
          Alabaster        122133.333333  123066.666667  123166.666667
          Albertville       73966.666667   72600.000000   72833.333333
          Arab              83766.666667   81566.666667   81333.333333
          Ardmore                    NaN            NaN            NaN
          Axis                       NaN            NaN            NaN
          Baileyton                  NaN            NaN            NaN
          Bay Minette       81700.000000   78533.333333   79133.333333
          Bayou La Batre    44066.666667   44500.000000   44266.666667
          Bessemer                   NaN            NaN            NaN
          Birmingham        54033.333333   54400.000000   54966.666667
          Boaz              70866.666667   70266.666667   70300.000000
          Brent             92933.333333   94333.333333   96166.666667
          Brighton                   NaN            NaN            NaN
          Brookwood         92566.666667   95100.000000   98866.666667
          Buhl              90800.000000   94600.000000   96500.000000
          Calera           108933.333333  110366.666667  108000.000000
          Center Point      80966.666667   81233.333333   81500.000000
          Centreville       95300.000000   96566.666667   98000.000000
          Chalkville        94100.000000   94433.333333   94433.333333
          Chancellor                 NaN            NaN            NaN
          Chelsea          162066.666667  167033.333333  166900.000000
          Chickasaw         51200.000000   53666.666667   54933.333333
          Chunchula         80266.666667   81766.666667   82200.000000
          Citronelle        64833.333333   66633.333333   68066.666667
          Clay             120900.000000  122266.666667  123966.666667
          Coden             62600.000000   64800.000000   66866.666667
          Coker            118100.000000  120766.666667  118166.666667
          Concord           78600.000000   78700.000000   80133.333333
          Cottondale       100833.333333  102633.333333  104766.666667
...                                  ...            ...            ...
Wisconsin Vernon           183200.000000  178200.000000  174300.000000
          Vienna           178033.333333  181533.333333  182433.333333
          Vinland          119800.000000  126766.666667  134933.333333
          Wales                      NaN            NaN            NaN
          Waterford        121200.000000  119433.333333  120200.000000
          Waukesha         141266.666667  138433.333333  136733.333333
          Waunakee         187400.000000  191433.333333  192666.666667
          Waupun            84000.000000   84000.000000   84400.000000
          Wausau            69566.666667   69466.666667   71033.333333
          Wayne                      NaN            NaN            NaN
          West Allis        80933.333333   81933.333333   84066.666667
          Weston            80166.666667   82700.000000   84166.666667
          Wheatland        129800.000000  132133.333333  134933.333333
          Whitelaw          96033.333333  101433.333333  108033.333333
          Williams Bay     122900.000000  115300.000000  110766.666667
          Wilson                     NaN            NaN            NaN
          Wilson           129033.333333  129366.666667  132433.333333
          Wind Lake        124366.666667  123666.666667  124133.333333
          Wind Point       149233.333333  145266.666667  140866.666667
          Wisconsin Dells  100000.000000  103400.000000  105000.000000
          Wolf River        95166.666667   99333.333333  103800.000000
          Woodruff                   NaN            NaN            NaN
          Woodville                  NaN            NaN            NaN
          Yorkville        139066.666667  134900.000000  135033.333333
Wyoming   Bar Nunn          93033.333333   89666.666667   88900.000000
          Burns            101533.333333  104566.666667  108366.666667
          Casper            89233.333333   89600.000000   89733.333333
          Cheyenne         116866.666667  120033.333333  121533.333333
          Evansville       128033.333333  128766.666667  130833.333333
          Pine Bluffs       93733.333333   95066.666667   94633.333333

quarter                           2000q4         2001q1         2001q2  \
State     RegionName
Alabama   Adamsville        71966.666667   73466.666667   74000.000000
          Alabaster        123700.000000  123233.333333  125133.333333
          Albertville       74200.000000   75900.000000   76000.000000
          Arab              82966.666667   84200.000000   84533.333333
          Ardmore                    NaN            NaN            NaN
          Axis                       NaN            NaN            NaN
          Baileyton                  NaN            NaN            NaN
          Bay Minette       81300.000000   85700.000000   87266.666667
          Bayou La Batre    43666.666667   42500.000000   43333.333333
          Bessemer                   NaN            NaN            NaN
          Birmingham        56066.666667   56833.333333   57600.000000
          Boaz              71466.666667   72833.333333   71900.000000
          Brent             98333.333333   96533.333333   98500.000000
          Brighton                   NaN            NaN            NaN
          Brookwood         99966.666667  101666.666667  103666.666667
          Buhl              96566.666667   99266.666667  101966.666667
          Calera           107933.333333  109333.333333  112200.000000
          Center Point      82233.333333   83366.666667   84333.333333
          Centreville       99366.666667   98100.000000   99266.666667
          Chalkville        94433.333333   96066.666667   97433.333333
          Chancellor                 NaN            NaN            NaN
          Chelsea          167400.000000  170633.333333  174300.000000
          Chickasaw         56066.666667   55133.333333   53566.666667
          Chunchula         83400.000000   85400.000000   86100.000000
          Citronelle        67766.666667   67866.666667   70000.000000
          Clay             126500.000000  128033.333333  128300.000000
          Coden             68566.666667   68933.333333   71300.000000
          Coker            115333.333333  114066.666667  115700.000000
          Concord           82800.000000   85133.333333   85800.000000
          Cottondale       105300.000000  106733.333333  109233.333333
...                                  ...            ...            ...
Wisconsin Vernon           177466.666667  186233.333333  190500.000000
          Vienna           186300.000000  190600.000000  191566.666667
          Vinland          137833.333333  144300.000000  148200.000000
          Wales                      NaN            NaN            NaN
          Waterford        121966.666667  127000.000000  133000.000000
          Waukesha         139833.333333  147600.000000  151066.666667
          Waunakee         193733.333333  197333.333333  198500.000000
          Waupun            84533.333333   85100.000000   86600.000000
          Wausau            69833.333333   69866.666667   71366.666667
          Wayne                      NaN            NaN            NaN
          West Allis        80666.666667   79100.000000   80333.333333
          Weston            85800.000000   87266.666667   88500.000000
          Wheatland        137833.333333  142566.666667  143000.000000
          Whitelaw         114000.000000  116333.333333  114966.666667
          Williams Bay     110700.000000  112600.000000  117100.000000
          Wilson                     NaN            NaN            NaN
          Wilson           137200.000000  143533.333333  143833.333333
          Wind Lake        126066.666667  132133.333333  139466.666667
          Wind Point       147866.666667  158666.666667  163966.666667
          Wisconsin Dells  105433.333333  105533.333333  107100.000000
          Wolf River       107633.333333  111400.000000  115033.333333
          Woodruff                   NaN            NaN            NaN
          Woodville                  NaN            NaN            NaN
          Yorkville        140300.000000  148800.000000  155233.333333
Wyoming   Bar Nunn          93500.000000   98833.333333   99900.000000
          Burns            113000.000000  115833.333333  117200.000000
          Casper            93166.666667   95500.000000   97633.333333
          Cheyenne         123633.333333  125533.333333  126300.000000
          Evansville       132066.666667  130566.666667  131433.333333
          Pine Bluffs       98066.666667  103233.333333  104600.000000

quarter                           2001q3         2001q4         2002q1  \
State     RegionName
Alabama   Adamsville        73333.333333   73100.000000   73333.333333
          Alabaster        127766.666667  127200.000000  127300.000000
          Albertville       72066.666667   73566.666667   76533.333333
          Arab              81666.666667   83900.000000   87266.666667
          Ardmore                    NaN            NaN            NaN
          Axis                       NaN            NaN            NaN
          Baileyton                  NaN            NaN            NaN
          Bay Minette       85900.000000   85000.000000   84066.666667
          Bayou La Batre    45433.333333   45400.000000   45400.000000
          Bessemer                   NaN            NaN            NaN
          Birmingham        58433.333333   58700.000000   59500.000000
          Boaz              68733.333333   69833.333333   72766.666667
          Brent             99366.666667  104100.000000  103800.000000
          Brighton                   NaN            NaN            NaN
          Brookwood        101833.333333   99900.000000   99633.333333
          Buhl             102000.000000  102733.333333  102533.333333
          Calera           114333.333333  112133.333333  111500.000000
          Center Point      84466.666667   85333.333333   86100.000000
          Centreville      100400.000000  104633.333333  105233.333333
          Chalkville        98400.000000   99366.666667   99866.666667
          Chancellor                 NaN            NaN            NaN
          Chelsea          174900.000000  173300.000000  170566.666667
          Chickasaw         53533.333333   53400.000000   54266.666667
          Chunchula         86733.333333   86566.666667   86166.666667
          Citronelle        71466.666667   70933.333333   69833.333333
          Clay             129233.333333  130466.666667  130900.000000
          Coden             72733.333333   73600.000000   72933.333333
          Coker            118833.333333  122566.666667  122366.666667
          Concord           84866.666667   84766.666667   86366.666667
          Cottondale       109200.000000  109900.000000  109333.333333
...                                  ...            ...            ...
Wisconsin Vernon           193100.000000  197466.666667  201800.000000
          Vienna           193733.333333  194833.333333  198466.666667
          Vinland          147733.333333  151200.000000  149233.333333
          Wales                      NaN            NaN            NaN
          Waterford        139233.333333  143100.000000  145733.333333
          Waukesha         153100.000000  155033.333333  158200.000000
          Waunakee         201266.666667  202100.000000  206100.000000
          Waupun            87666.666667   87100.000000   87533.333333
          Wausau            73100.000000   74033.333333   76400.000000
          Wayne                      NaN            NaN            NaN
          West Allis        81433.333333   82400.000000   84966.666667
          Weston            90066.666667   91766.666667   94833.333333
          Wheatland        143966.666667  142633.333333  143933.333333
          Whitelaw         115666.666667  115866.666667  117766.666667
          Williams Bay     119533.333333  121400.000000  126566.666667
          Wilson                     NaN            NaN            NaN
          Wilson           143233.333333  141966.666667  142466.666667
          Wind Lake        144200.000000  147333.333333  150933.333333
          Wind Point       170833.333333  169566.666667  170533.333333
          Wisconsin Dells  109866.666667  111633.333333  115833.333333
          Wolf River       116900.000000  118233.333333  118600.000000
          Woodruff                   NaN            NaN            NaN
          Woodville                  NaN            NaN            NaN
          Yorkville        161133.333333  162800.000000  164866.666667
Wyoming   Bar Nunn          99100.000000   98333.333333   98633.333333
          Burns            117800.000000  117633.333333  117333.333333
          Casper            99433.333333  100633.333333  101733.333333
          Cheyenne         126466.666667  128133.333333  128466.666667
          Evansville       132400.000000  133466.666667  133300.000000
          Pine Bluffs      106500.000000  104066.666667  102233.333333

quarter                           2002q2    ...            2014q2  \
State     RegionName                        ...
Alabama   Adamsville        73133.333333    ...      77066.666667
          Alabaster        128000.000000    ...     147133.333333
          Albertville       76366.666667    ...      84033.333333
          Arab              87700.000000    ...     113366.666667
          Ardmore                    NaN    ...     140533.333333
          Axis                       NaN    ...     111066.666667
          Baileyton                  NaN    ...      87666.666667
          Bay Minette       84566.666667    ...     113333.333333
          Bayou La Batre    45566.666667    ...      49800.000000
          Bessemer                   NaN    ...      54600.000000
          Birmingham        59866.666667    ...      61733.333333
          Boaz              72100.000000    ...      80933.333333
          Brent            102533.333333    ...      93866.666667
          Brighton                   NaN    ...      45366.666667
          Brookwood        100366.666667    ...     106633.333333
          Buhl             100100.000000    ...     119233.333333
          Calera           111233.333333    ...     125533.333333
          Center Point      86500.000000    ...      78833.333333
          Centreville      105066.666667    ...      95566.666667
          Chalkville       100733.333333    ...     105233.333333
          Chancellor                 NaN    ...     116400.000000
          Chelsea          171100.000000    ...     197133.333333
          Chickasaw         55000.000000    ...      59000.000000
          Chunchula         86533.333333    ...     120666.666667
          Citronelle        68133.333333    ...      88600.000000
          Clay             131100.000000    ...     134100.000000
          Coden             69100.000000    ...      77566.666667
          Coker            119200.000000    ...     141700.000000
          Concord           90366.666667    ...     104733.333333
          Cottondale       107966.666667    ...     128500.000000
...                                  ...    ...               ...
Wisconsin Vernon           201966.666667    ...     257733.333333
          Vienna           202466.666667    ...     265700.000000
          Vinland          146433.333333    ...     181766.666667
          Wales                      NaN    ...     262133.333333
          Waterford        151266.666667    ...     213133.333333
          Waukesha         157833.333333    ...     181166.666667
          Waunakee         208533.333333    ...     278100.000000
          Waupun            87466.666667    ...     113166.666667
          Wausau            78700.000000    ...      91600.000000
          Wayne                      NaN    ...     238633.333333
          West Allis        87566.666667    ...      90433.333333
          Weston            97600.000000    ...     133233.333333
          Wheatland        146433.333333    ...     169266.666667
          Whitelaw         116800.000000    ...     120433.333333
          Williams Bay     131700.000000    ...     223000.000000
          Wilson                     NaN    ...     170300.000000
          Wilson           139200.000000    ...     159933.333333
          Wind Lake        156166.666667    ...     228200.000000
          Wind Point       179733.333333    ...     261233.333333
          Wisconsin Dells  117333.333333    ...     137500.000000
          Wolf River       116800.000000    ...     162666.666667
          Woodruff                   NaN    ...     172133.333333
          Woodville                  NaN    ...     162600.000000
          Yorkville        172466.666667    ...     231500.000000
Wyoming   Bar Nunn         100866.666667    ...     199233.333333
          Burns            117233.333333    ...     168866.666667
          Casper           101533.333333    ...     175766.666667
          Cheyenne         129633.333333    ...     177466.666667
          Evansville       131066.666667    ...     296733.333333
          Pine Bluffs      103566.666667    ...     148666.666667

quarter                           2014q3         2014q4         2015q1  \
State     RegionName
Alabama   Adamsville        75966.666667   71900.000000   71666.666667
          Alabaster        147633.333333  148700.000000  148900.000000
          Albertville       84766.666667   86800.000000   88466.666667
          Arab             111700.000000  111600.000000  110166.666667
          Ardmore          139566.666667  140900.000000  143233.333333
          Axis             111833.333333  111800.000000  109533.333333
          Baileyton         90033.333333   94100.000000   94600.000000
          Bay Minette      110600.000000  109900.000000  111100.000000
          Bayou La Batre    51000.000000   51766.666667   50733.333333
          Bessemer          55333.333333   54733.333333   55200.000000
          Birmingham        60900.000000   59533.333333   59900.000000
          Boaz              81866.666667   82866.666667   83966.666667
          Brent             97100.000000  100100.000000  102433.333333
          Brighton          45133.333333   43766.666667   42500.000000
          Brookwood        110233.333333  114366.666667  117700.000000
          Buhl             132033.333333  138400.000000  141766.666667
          Calera           126733.333333  127633.333333  128366.666667
          Center Point      78433.333333   80200.000000   80100.000000
          Centreville       98866.666667  101866.666667  103933.333333
          Chalkville       104333.333333  105866.666667  106966.666667
          Chancellor       117000.000000  117133.333333  114733.333333
          Chelsea          199066.666667  199933.333333  202333.333333
          Chickasaw         60400.000000   59733.333333   58066.666667
          Chunchula        121600.000000  122733.333333  123666.666667
          Citronelle        89633.333333   90766.666667   91300.000000
          Clay             134300.000000  135466.666667  138466.666667
          Coden             76866.666667   77800.000000   79300.000000
          Coker            146300.000000  154333.333333  157566.666667
          Concord          100233.333333   94800.000000   96200.000000
          Cottondale       130566.666667  133433.333333  134500.000000
...                                  ...            ...            ...
Wisconsin Vernon           256200.000000  254566.666667  253633.333333
          Vienna           267466.666667  267766.666667  268300.000000
          Vinland          183500.000000  184233.333333  184033.333333

In [13]:
def run_ttest():
    '''First creates new data showing the decline or growth of housing prices
    between the recession start and the recession bottom. Then runs a ttest
    comparing the university town values to the non-university towns values, 
    return whether the alternative hypothesis (that the two groups are the same)
    is true or not as well as the p-value of the confidence. 

    Return the tuple (different, p, better) where different=True if the t-test is
    True at a p<0.01 (we reject the null hypothesis), or different=False if 
    otherwise (we cannot reject the null hypothesis). The variable p should
    be equal to the exact p value returned from scipy.stats.ttest_ind(). The
    value for better should be either "university town" or "non-university town"
    depending on which has a lower mean price ratio (which is equivilent to a
    reduced market loss).'''

    import pandas as pd
    import numpy as np
    from scipy.stats import ttest_ind

    univ_towns = get_list_of_university_towns()
    univ_towns['univ_town'] = True

    # merge the housing data with university town DataFrames
    df = pd.merge(convert_housing_data_to_quarters(), univ_towns, how='outer', left_index=True, right_on=['State', 'RegionName'])
    df['univ_town'] = df['univ_town'].replace({np.NaN: False})

    # Get the recession quarters
    recession_start = get_recession_start()
    recession_bottom = get_recession_bottom()

    # Parse the year and quarter of the recession quarters
    year_recession_start = int(recession_start[0:4])
    qtr_recession_start = int(recession_start[-1])
    year_recession_bottom = int(recession_bottom[0:4])
    qtr_recession_bottom = int(recession_bottom[-1])

    # get the columns to keep in the merged DataFrame
    cols_to_keep = ['State', 'RegionName', 'univ_town']
    qtrs_to_keep = []
    for i in range(year_recession_start, year_recession_bottom+1):
        for j in range(1, 5):
            if (i == year_recession_start and j < qtr_recession_start)\
                    or (i == year_recession_bottom and j > qtr_recession_bottom):
                pass
            else:
                qtrs_to_keep.append(str(i) + 'q' + str(j))
    df = df[cols_to_keep + qtrs_to_keep]

    # Compute the price_ratio
    df['price_ratio'] = df[recession_bottom] - df[recession_start]

    # t-test to determine if there is a difference between university and non-university towns
    univ_town_price_ratio = df[df['univ_town'] == True]['price_ratio']
    non_univ_town_price_ratio = df[df['univ_town'] == False]['price_ratio']
    st, p = ttest_ind(univ_town_price_ratio, non_univ_town_price_ratio, nan_policy='omit',)

    # get different and better values
    different = False
    if p < 0.01:
        different = True

    # determine which type of town is better
    better = ""
    if univ_town_price_ratio.mean() > non_univ_town_price_ratio.mean():
        better = "university town"
    else:
        better = "non-university town"

    return (different, p, better)

run_ttest()

(True, 0.0043252148534599624, 'university town')